### ISSUE TITLE
Feature request: some improvements

### ISSUE THREAD

**Issue by LinArcX** [tamago324/vim-clap-help#1]
Hi, thank you for this provider. i have some suggestions to improve it:

1. It doesn't have preview for each page, like `grep provider`. 
2. It's slow. because it should search between more than 10.000 search results, So i think we need some tweaks to make it faster and smoother.

**Comment by tamago324** [comment]
Hi, thanks for the suggestions.

> 1. It doesn't have preview for each page, like grep provider.

I want to implement.

> 2. It's slow.because it should search between more than 10.000 search results, So i think we need some tweaks to make it faster and smoother.

It is not immediately possible to determine if you can adjust with vim-clap-help.
After reading the source code of vim-clap, I will judge.
If you know how to improve, please let me know.

**Comment by tamago324** [comment]
@LinArcX vim-clap It seems good to use the standard help_tags provider.

See https://github.com/liuchengxu/vim-clap/pull/248

**Comment by LinArcX** [comment]
Yeah, i saw it. thanks.
